### 4.退出登入功能
GET http://localhost:8080/v1/users/logout
Accept: application/json

### 3.獲取登入狀態
GET http://localhost:8080/v1/users/currentUser
Accept: application/json

### 2.登入功能測試
POST http://localhost:8080/v1/users/login
Content-Type: application/json

{
  "username": "Lucy",
  "password": "123456"
}

### 1.註冊功能測試 - JSON
POST http://localhost:8080/v1/users/reg
Content-Type: application/json

{
  "username": "Dilireba",
  "password": "123456",
  "nickname": "dilireba"
}