GET http://localhost:8080/emp/delete?id=1
Accept: application/json

###
GET http://localhost:8080/emp/update?id=2&title=高級工程師&salary=400000.0&job=網頁設計
Accept: application/json

###
GET http://localhost:8080/emp/select
Accept: application/json

###
POST http://localhost:8080/emp/insert
Content-Type: application/x-www-form-urlencoded

title=中級工程師&salary=300000.0&job=前端開發

###
