# ############################################################################################### #
# 此文件是【開發環境】的配置文件，必須在主配置中通過spring.profiles.active激活此配置，此文件中的各配置才會生效 #
# ############################################################################################### #

# 服務器的配置
server:
  # 服務占用的端口
  port: 28281

# 自定義配置
nike:
  # 數據庫的數據源的配置
  datasource:
    # 數據庫主機
    host: localhost
    # 數據庫端口
    port: 3306
    # 數據庫用戶名
    username: root
    # 數據庫密碼
    password: root
    # 初始化連接數量
    initial-size: 5
    # 最大激活數量
    max-active: 20
  # Redis配置
  redis:
    # 主機
    host: localhost
    # 端口
    port: 6379
    # 用戶名
    username: ~
    # 密碼
    password: ~
  # 數據訪問的相關配置
  dao:
    # 查詢數據時，默認的每頁記錄數，建議值為10~30之間
    default-query-page-size: 10
  # JWT的配置
  jwt:
    # JWT的有效時長，以分鐘為單位
    duration-in-minute: 86400
    # JWT的secretKey
    secret-key: k4^&32flj5Ss(Jf&*(5%DK3da

# 日志配置
logging:
  # 顯示級別
  level:
    # 某根包（配置將應用於此包及子孫包）的顯示級別
    com.yafeng.nike: trace