### 3.身体健康指數測試
GET http://localhost:8080/bmi?height=1.55&weight=90.0
Accept: application/json

### 2.測試登入功能[POST]
POST http://localhost:8080/v1/users/login
Content-Type: application/x-www-form-urlencoded

username=hikyu&password=123456


### 1.測試登入功能[GET]
GET http://localhost:8080/v1/users/login?username=hikyu&password=123456
Accept: application/json






